export const CHANGE_THEME = 'CHANGE_THEME';
export const SEARCH = 'SEARCH';
export const SET_PARAM = 'SET_PARAM';
export const SET_VIDEO = 'SET_VIDEO';
export const SET_LIST_OF_VIDEOS = 'SET_LIST_OF_VIDEOS';
export const SET_ERROR = 'SET_ERROR';
export const UPDATE_FAVORITES_SELECTED_VIDEO = 'UPDATE_FAVORITES_SELECTED_VIDEO';
export const UPDATE_FAVORITES_LIST_OF_VIDEOS = 'UPDATE_FAVORITES_LIST_OF_VIDEOS';
