export const CHANGE_THEME = 'CHANGE_THEME';
export const SET_PARAM = 'SET_PARAM';
export const SET_VIDEO = 'SET_VIDEO';
export const SET_LIST_OF_VIDEOS = 'SET_LIST_OF_VIDEOS';
export const SET_ERROR = 'SET_ERROR';
export const UPDATE_FAVORITE_VIDEOS = 'UPDATE_FAVORITE_VIDEOS';
